// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users_srv.proto

package users

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserRegistrationRequest struct {
	FirstName            string    `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string    `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	EmailId              string    `protobuf:"bytes,3,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	Password             string    `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword      string    `protobuf:"bytes,5,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	Tags                 string    `protobuf:"bytes,6,opt,name=tags,proto3" json:"tags,omitempty"`
	Location             *Location `protobuf:"bytes,7,opt,name=Location,proto3" json:"Location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserRegistrationRequest) Reset()         { *m = UserRegistrationRequest{} }
func (m *UserRegistrationRequest) String() string { return proto.CompactTextString(m) }
func (*UserRegistrationRequest) ProtoMessage()    {}
func (*UserRegistrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{0}
}

func (m *UserRegistrationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegistrationRequest.Unmarshal(m, b)
}
func (m *UserRegistrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegistrationRequest.Marshal(b, m, deterministic)
}
func (m *UserRegistrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegistrationRequest.Merge(m, src)
}
func (m *UserRegistrationRequest) XXX_Size() int {
	return xxx_messageInfo_UserRegistrationRequest.Size(m)
}
func (m *UserRegistrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegistrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegistrationRequest proto.InternalMessageInfo

func (m *UserRegistrationRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserRegistrationRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserRegistrationRequest) GetEmailId() string {
	if m != nil {
		return m.EmailId
	}
	return ""
}

func (m *UserRegistrationRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserRegistrationRequest) GetConfirmPassword() string {
	if m != nil {
		return m.ConfirmPassword
	}
	return ""
}

func (m *UserRegistrationRequest) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *UserRegistrationRequest) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type Location struct {
	Lat                  float32  `protobuf:"fixed32,1,opt,name=Lat,proto3" json:"Lat,omitempty"`
	Lng                  float32  `protobuf:"fixed32,2,opt,name=Lng,proto3" json:"Lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{1}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Location) GetLng() float32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

type UserRegistrationResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegistrationResponse) Reset()         { *m = UserRegistrationResponse{} }
func (m *UserRegistrationResponse) String() string { return proto.CompactTextString(m) }
func (*UserRegistrationResponse) ProtoMessage()    {}
func (*UserRegistrationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{2}
}

func (m *UserRegistrationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegistrationResponse.Unmarshal(m, b)
}
func (m *UserRegistrationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegistrationResponse.Marshal(b, m, deterministic)
}
func (m *UserRegistrationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegistrationResponse.Merge(m, src)
}
func (m *UserRegistrationResponse) XXX_Size() int {
	return xxx_messageInfo_UserRegistrationResponse.Size(m)
}
func (m *UserRegistrationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegistrationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegistrationResponse proto.InternalMessageInfo

func (m *UserRegistrationResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UserRegistrationResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UserLoginRequest struct {
	EmailId              string    `protobuf:"bytes,1,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	Password             string    `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Location             *Location `protobuf:"bytes,3,opt,name=Location,proto3" json:"Location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserLoginRequest) Reset()         { *m = UserLoginRequest{} }
func (m *UserLoginRequest) String() string { return proto.CompactTextString(m) }
func (*UserLoginRequest) ProtoMessage()    {}
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{3}
}

func (m *UserLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginRequest.Unmarshal(m, b)
}
func (m *UserLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginRequest.Marshal(b, m, deterministic)
}
func (m *UserLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginRequest.Merge(m, src)
}
func (m *UserLoginRequest) XXX_Size() int {
	return xxx_messageInfo_UserLoginRequest.Size(m)
}
func (m *UserLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginRequest proto.InternalMessageInfo

func (m *UserLoginRequest) GetEmailId() string {
	if m != nil {
		return m.EmailId
	}
	return ""
}

func (m *UserLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserLoginRequest) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type UserLoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginResponse) Reset()         { *m = UserLoginResponse{} }
func (m *UserLoginResponse) String() string { return proto.CompactTextString(m) }
func (*UserLoginResponse) ProtoMessage()    {}
func (*UserLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{4}
}

func (m *UserLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginResponse.Unmarshal(m, b)
}
func (m *UserLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginResponse.Marshal(b, m, deterministic)
}
func (m *UserLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginResponse.Merge(m, src)
}
func (m *UserLoginResponse) XXX_Size() int {
	return xxx_messageInfo_UserLoginResponse.Size(m)
}
func (m *UserLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginResponse proto.InternalMessageInfo

func (m *UserLoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UserLoginResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func init() {
	proto.RegisterType((*UserRegistrationRequest)(nil), "users.UserRegistrationRequest")
	proto.RegisterType((*Location)(nil), "users.Location")
	proto.RegisterType((*UserRegistrationResponse)(nil), "users.UserRegistrationResponse")
	proto.RegisterType((*UserLoginRequest)(nil), "users.UserLoginRequest")
	proto.RegisterType((*UserLoginResponse)(nil), "users.UserLoginResponse")
}

func init() {
	proto.RegisterFile("users_srv.proto", fileDescriptor_516d2df10a1d8884)
}

var fileDescriptor_516d2df10a1d8884 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x49, 0x93, 0xd8, 0x03, 0x28, 0x61, 0x05, 0xca, 0x12, 0x04, 0x54, 0xe6, 0x52, 0x84,
	0xe4, 0x43, 0x79, 0x01, 0xae, 0x95, 0xd2, 0x0a, 0x19, 0x7a, 0xb6, 0x16, 0x7b, 0x62, 0x56, 0xd4,
	0xbb, 0x61, 0x67, 0x13, 0x5e, 0x8b, 0xc7, 0xe3, 0x88, 0x76, 0xfc, 0x83, 0x45, 0x15, 0xf5, 0xb6,
	0xdf, 0x4f, 0x66, 0xe6, 0xfb, 0x14, 0xc3, 0xf2, 0x40, 0xe8, 0xa8, 0x20, 0x77, 0xcc, 0xf6, 0xce,
	0x7a, 0x2b, 0x66, 0x4c, 0xa4, 0x7f, 0x22, 0x58, 0xdf, 0x12, 0xba, 0x1c, 0x6b, 0x4d, 0xde, 0x29,
	0xaf, 0xad, 0xc9, 0xf1, 0xe7, 0x01, 0xc9, 0x8b, 0xd7, 0x00, 0x3b, 0xed, 0xc8, 0x17, 0x46, 0x35,
	0x28, 0xa3, 0xf3, 0xe8, 0x22, 0xc9, 0x13, 0x66, 0x6e, 0x54, 0x83, 0xe2, 0x15, 0x24, 0x77, 0xaa,
	0x57, 0x27, 0xac, 0xc6, 0x81, 0x60, 0xf1, 0x25, 0xc4, 0xd8, 0x28, 0x7d, 0x57, 0xe8, 0x4a, 0x4e,
	0x59, 0x5b, 0x30, 0xbe, 0xaa, 0xc4, 0x06, 0xe2, 0xbd, 0x22, 0xfa, 0x65, 0x5d, 0x25, 0xcf, 0xda,
	0x9f, 0xf5, 0x58, 0xbc, 0x87, 0x55, 0x69, 0xcd, 0x4e, 0xbb, 0xa6, 0x18, 0x3c, 0x33, 0xf6, 0x2c,
	0x3b, 0xfe, 0x73, 0x6f, 0x15, 0x70, 0xe6, 0x55, 0x4d, 0x72, 0xce, 0x32, 0xbf, 0xc5, 0x07, 0x88,
	0xb7, 0xb6, 0xe4, 0x10, 0x72, 0x71, 0x1e, 0x5d, 0x3c, 0xbe, 0x5c, 0x66, 0x9c, 0x33, 0xeb, 0xe9,
	0x7c, 0x30, 0xa4, 0xd9, 0x3f, 0xb3, 0x58, 0xc1, 0x74, 0xab, 0x3c, 0x67, 0x9c, 0xe4, 0xe1, 0xc9,
	0x8c, 0xa9, 0x39, 0x57, 0x60, 0x4c, 0x9d, 0x5e, 0x83, 0xbc, 0xdf, 0x14, 0xed, 0xad, 0x21, 0x14,
	0x12, 0x16, 0x74, 0x28, 0x4b, 0x24, 0xe2, 0x19, 0x71, 0xde, 0x43, 0xb1, 0x86, 0x45, 0xb8, 0x20,
	0xf4, 0xd0, 0x76, 0x34, 0x0f, 0xf0, 0xaa, 0x4a, 0x8f, 0xb0, 0x0a, 0xe3, 0xb6, 0xb6, 0xd6, 0x43,
	0xe3, 0xe3, 0xd6, 0xa2, 0xd3, 0xad, 0x4d, 0xfe, 0x6b, 0x6d, 0x1c, 0x7b, 0xfa, 0x50, 0xec, 0x1b,
	0x78, 0x36, 0xda, 0xdb, 0xdd, 0xff, 0x1c, 0x66, 0xde, 0xfe, 0x40, 0xd3, 0x6d, 0x6d, 0x81, 0x78,
	0x07, 0x4f, 0x1d, 0xee, 0x1c, 0xd2, 0xf7, 0xa2, 0x55, 0xdb, 0xc5, 0x4f, 0x3a, 0xf2, 0x6b, 0xe0,
	0x2e, 0x7f, 0x47, 0xf0, 0x22, 0x0c, 0xbc, 0x56, 0x46, 0xd5, 0xd8, 0xa0, 0xf1, 0x5f, 0xd0, 0x1d,
	0x75, 0x89, 0xe2, 0xb6, 0x4d, 0x38, 0x2e, 0x4c, 0xbc, 0xe9, 0x0e, 0x3b, 0xf1, 0x9f, 0xdb, 0xbc,
	0x3d, 0xa9, 0xb7, 0x97, 0xa6, 0x8f, 0xc4, 0x27, 0x48, 0x86, 0x00, 0x62, 0x3d, 0xf2, 0x8f, 0xab,
	0xdc, 0xc8, 0xfb, 0x42, 0x3f, 0xe1, 0xdb, 0x9c, 0x3f, 0x81, 0x8f, 0x7f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x2d, 0xe4, 0x42, 0x8b, 0x15, 0x03, 0x00, 0x00,
}
