// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users_srv.proto

package users

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserRegistrationRequest struct {
	FirstName            string    `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string    `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	EmailId              string    `protobuf:"bytes,3,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	Password             string    `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword      string    `protobuf:"bytes,5,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	Tags                 string    `protobuf:"bytes,6,opt,name=tags,proto3" json:"tags,omitempty"`
	Location             *Location `protobuf:"bytes,7,opt,name=Location,proto3" json:"Location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserRegistrationRequest) Reset()         { *m = UserRegistrationRequest{} }
func (m *UserRegistrationRequest) String() string { return proto.CompactTextString(m) }
func (*UserRegistrationRequest) ProtoMessage()    {}
func (*UserRegistrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{0}
}

func (m *UserRegistrationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegistrationRequest.Unmarshal(m, b)
}
func (m *UserRegistrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegistrationRequest.Marshal(b, m, deterministic)
}
func (m *UserRegistrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegistrationRequest.Merge(m, src)
}
func (m *UserRegistrationRequest) XXX_Size() int {
	return xxx_messageInfo_UserRegistrationRequest.Size(m)
}
func (m *UserRegistrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegistrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegistrationRequest proto.InternalMessageInfo

func (m *UserRegistrationRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserRegistrationRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserRegistrationRequest) GetEmailId() string {
	if m != nil {
		return m.EmailId
	}
	return ""
}

func (m *UserRegistrationRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserRegistrationRequest) GetConfirmPassword() string {
	if m != nil {
		return m.ConfirmPassword
	}
	return ""
}

func (m *UserRegistrationRequest) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *UserRegistrationRequest) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type Location struct {
	Lat                  float32  `protobuf:"fixed32,1,opt,name=Lat,proto3" json:"Lat,omitempty"`
	Lng                  float32  `protobuf:"fixed32,2,opt,name=Lng,proto3" json:"Lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{1}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Location) GetLng() float32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

type UserRegistrationResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegistrationResponse) Reset()         { *m = UserRegistrationResponse{} }
func (m *UserRegistrationResponse) String() string { return proto.CompactTextString(m) }
func (*UserRegistrationResponse) ProtoMessage()    {}
func (*UserRegistrationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{2}
}

func (m *UserRegistrationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegistrationResponse.Unmarshal(m, b)
}
func (m *UserRegistrationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegistrationResponse.Marshal(b, m, deterministic)
}
func (m *UserRegistrationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegistrationResponse.Merge(m, src)
}
func (m *UserRegistrationResponse) XXX_Size() int {
	return xxx_messageInfo_UserRegistrationResponse.Size(m)
}
func (m *UserRegistrationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegistrationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegistrationResponse proto.InternalMessageInfo

func (m *UserRegistrationResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UserRegistrationResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UserLoginRequest struct {
	EmailId              string    `protobuf:"bytes,1,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	Password             string    `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Location             *Location `protobuf:"bytes,3,opt,name=Location,proto3" json:"Location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserLoginRequest) Reset()         { *m = UserLoginRequest{} }
func (m *UserLoginRequest) String() string { return proto.CompactTextString(m) }
func (*UserLoginRequest) ProtoMessage()    {}
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{3}
}

func (m *UserLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginRequest.Unmarshal(m, b)
}
func (m *UserLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginRequest.Marshal(b, m, deterministic)
}
func (m *UserLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginRequest.Merge(m, src)
}
func (m *UserLoginRequest) XXX_Size() int {
	return xxx_messageInfo_UserLoginRequest.Size(m)
}
func (m *UserLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginRequest proto.InternalMessageInfo

func (m *UserLoginRequest) GetEmailId() string {
	if m != nil {
		return m.EmailId
	}
	return ""
}

func (m *UserLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserLoginRequest) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type UserLoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginResponse) Reset()         { *m = UserLoginResponse{} }
func (m *UserLoginResponse) String() string { return proto.CompactTextString(m) }
func (*UserLoginResponse) ProtoMessage()    {}
func (*UserLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{4}
}

func (m *UserLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginResponse.Unmarshal(m, b)
}
func (m *UserLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginResponse.Marshal(b, m, deterministic)
}
func (m *UserLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginResponse.Merge(m, src)
}
func (m *UserLoginResponse) XXX_Size() int {
	return xxx_messageInfo_UserLoginResponse.Size(m)
}
func (m *UserLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginResponse proto.InternalMessageInfo

func (m *UserLoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UserLoginResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type ListUserRequests struct {
	All                  string   `protobuf:"bytes,1,opt,name=all,proto3" json:"all,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserRequests) Reset()         { *m = ListUserRequests{} }
func (m *ListUserRequests) String() string { return proto.CompactTextString(m) }
func (*ListUserRequests) ProtoMessage()    {}
func (*ListUserRequests) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{5}
}

func (m *ListUserRequests) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserRequests.Unmarshal(m, b)
}
func (m *ListUserRequests) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserRequests.Marshal(b, m, deterministic)
}
func (m *ListUserRequests) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserRequests.Merge(m, src)
}
func (m *ListUserRequests) XXX_Size() int {
	return xxx_messageInfo_ListUserRequests.Size(m)
}
func (m *ListUserRequests) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserRequests.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserRequests proto.InternalMessageInfo

func (m *ListUserRequests) GetAll() string {
	if m != nil {
		return m.All
	}
	return ""
}

type ListUserResponse struct {
	FirstName            string    `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string    `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	EmailId              string    `protobuf:"bytes,3,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	Password             string    `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword      string    `protobuf:"bytes,5,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	Tags                 string    `protobuf:"bytes,6,opt,name=tags,proto3" json:"tags,omitempty"`
	Location             *Location `protobuf:"bytes,7,opt,name=Location,proto3" json:"Location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListUserResponse) Reset()         { *m = ListUserResponse{} }
func (m *ListUserResponse) String() string { return proto.CompactTextString(m) }
func (*ListUserResponse) ProtoMessage()    {}
func (*ListUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{6}
}

func (m *ListUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserResponse.Unmarshal(m, b)
}
func (m *ListUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserResponse.Marshal(b, m, deterministic)
}
func (m *ListUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserResponse.Merge(m, src)
}
func (m *ListUserResponse) XXX_Size() int {
	return xxx_messageInfo_ListUserResponse.Size(m)
}
func (m *ListUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserResponse proto.InternalMessageInfo

func (m *ListUserResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *ListUserResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *ListUserResponse) GetEmailId() string {
	if m != nil {
		return m.EmailId
	}
	return ""
}

func (m *ListUserResponse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ListUserResponse) GetConfirmPassword() string {
	if m != nil {
		return m.ConfirmPassword
	}
	return ""
}

func (m *ListUserResponse) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *ListUserResponse) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type CreateRoleRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoleRequest) Reset()         { *m = CreateRoleRequest{} }
func (m *CreateRoleRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRoleRequest) ProtoMessage()    {}
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{7}
}

func (m *CreateRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoleRequest.Unmarshal(m, b)
}
func (m *CreateRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoleRequest.Marshal(b, m, deterministic)
}
func (m *CreateRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoleRequest.Merge(m, src)
}
func (m *CreateRoleRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRoleRequest.Size(m)
}
func (m *CreateRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoleRequest proto.InternalMessageInfo

func (m *CreateRoleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRoleRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateRoleResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RoleId               string   `protobuf:"bytes,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoleResponse) Reset()         { *m = CreateRoleResponse{} }
func (m *CreateRoleResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRoleResponse) ProtoMessage()    {}
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{8}
}

func (m *CreateRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoleResponse.Unmarshal(m, b)
}
func (m *CreateRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoleResponse.Marshal(b, m, deterministic)
}
func (m *CreateRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoleResponse.Merge(m, src)
}
func (m *CreateRoleResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRoleResponse.Size(m)
}
func (m *CreateRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoleResponse proto.InternalMessageInfo

func (m *CreateRoleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateRoleResponse) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

type CreatePermissionRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePermissionRequest) Reset()         { *m = CreatePermissionRequest{} }
func (m *CreatePermissionRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePermissionRequest) ProtoMessage()    {}
func (*CreatePermissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{9}
}

func (m *CreatePermissionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePermissionRequest.Unmarshal(m, b)
}
func (m *CreatePermissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePermissionRequest.Marshal(b, m, deterministic)
}
func (m *CreatePermissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePermissionRequest.Merge(m, src)
}
func (m *CreatePermissionRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePermissionRequest.Size(m)
}
func (m *CreatePermissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePermissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePermissionRequest proto.InternalMessageInfo

func (m *CreatePermissionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreatePermissionRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreatePermissionResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PermissionId         string   `protobuf:"bytes,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePermissionResponse) Reset()         { *m = CreatePermissionResponse{} }
func (m *CreatePermissionResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePermissionResponse) ProtoMessage()    {}
func (*CreatePermissionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{10}
}

func (m *CreatePermissionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePermissionResponse.Unmarshal(m, b)
}
func (m *CreatePermissionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePermissionResponse.Marshal(b, m, deterministic)
}
func (m *CreatePermissionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePermissionResponse.Merge(m, src)
}
func (m *CreatePermissionResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePermissionResponse.Size(m)
}
func (m *CreatePermissionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePermissionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePermissionResponse proto.InternalMessageInfo

func (m *CreatePermissionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreatePermissionResponse) GetPermissionId() string {
	if m != nil {
		return m.PermissionId
	}
	return ""
}

type CreateTagRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTagRequest) Reset()         { *m = CreateTagRequest{} }
func (m *CreateTagRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTagRequest) ProtoMessage()    {}
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{11}
}

func (m *CreateTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTagRequest.Unmarshal(m, b)
}
func (m *CreateTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTagRequest.Marshal(b, m, deterministic)
}
func (m *CreateTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTagRequest.Merge(m, src)
}
func (m *CreateTagRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTagRequest.Size(m)
}
func (m *CreateTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTagRequest proto.InternalMessageInfo

func (m *CreateTagRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateTagRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateTagResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TagId                string   `protobuf:"bytes,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTagResponse) Reset()         { *m = CreateTagResponse{} }
func (m *CreateTagResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTagResponse) ProtoMessage()    {}
func (*CreateTagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{12}
}

func (m *CreateTagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTagResponse.Unmarshal(m, b)
}
func (m *CreateTagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTagResponse.Marshal(b, m, deterministic)
}
func (m *CreateTagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTagResponse.Merge(m, src)
}
func (m *CreateTagResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTagResponse.Size(m)
}
func (m *CreateTagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTagResponse proto.InternalMessageInfo

func (m *CreateTagResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateTagResponse) GetTagId() string {
	if m != nil {
		return m.TagId
	}
	return ""
}

type AttachRolesPermissionsRequest struct {
	Roles                []int64  `protobuf:"varint,1,rep,packed,name=roles,proto3" json:"roles,omitempty"`
	Permissions          []int64  `protobuf:"varint,2,rep,packed,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachRolesPermissionsRequest) Reset()         { *m = AttachRolesPermissionsRequest{} }
func (m *AttachRolesPermissionsRequest) String() string { return proto.CompactTextString(m) }
func (*AttachRolesPermissionsRequest) ProtoMessage()    {}
func (*AttachRolesPermissionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{13}
}

func (m *AttachRolesPermissionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachRolesPermissionsRequest.Unmarshal(m, b)
}
func (m *AttachRolesPermissionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachRolesPermissionsRequest.Marshal(b, m, deterministic)
}
func (m *AttachRolesPermissionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachRolesPermissionsRequest.Merge(m, src)
}
func (m *AttachRolesPermissionsRequest) XXX_Size() int {
	return xxx_messageInfo_AttachRolesPermissionsRequest.Size(m)
}
func (m *AttachRolesPermissionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachRolesPermissionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AttachRolesPermissionsRequest proto.InternalMessageInfo

func (m *AttachRolesPermissionsRequest) GetRoles() []int64 {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *AttachRolesPermissionsRequest) GetPermissions() []int64 {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type AttachRolesPermissionsResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachRolesPermissionsResponse) Reset()         { *m = AttachRolesPermissionsResponse{} }
func (m *AttachRolesPermissionsResponse) String() string { return proto.CompactTextString(m) }
func (*AttachRolesPermissionsResponse) ProtoMessage()    {}
func (*AttachRolesPermissionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{14}
}

func (m *AttachRolesPermissionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachRolesPermissionsResponse.Unmarshal(m, b)
}
func (m *AttachRolesPermissionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachRolesPermissionsResponse.Marshal(b, m, deterministic)
}
func (m *AttachRolesPermissionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachRolesPermissionsResponse.Merge(m, src)
}
func (m *AttachRolesPermissionsResponse) XXX_Size() int {
	return xxx_messageInfo_AttachRolesPermissionsResponse.Size(m)
}
func (m *AttachRolesPermissionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachRolesPermissionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AttachRolesPermissionsResponse proto.InternalMessageInfo

func (m *AttachRolesPermissionsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AttachUsersRolesRequest struct {
	Roles                []int64                                     `protobuf:"varint,1,rep,packed,name=roles,proto3" json:"roles,omitempty"`
	Users                []int64                                     `protobuf:"varint,2,rep,packed,name=users,proto3" json:"users,omitempty"`
	Role                 map[string]*AttachUsersRolesRequestUsersMap `protobuf:"bytes,3,rep,name=role,proto3" json:"role,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *AttachUsersRolesRequest) Reset()         { *m = AttachUsersRolesRequest{} }
func (m *AttachUsersRolesRequest) String() string { return proto.CompactTextString(m) }
func (*AttachUsersRolesRequest) ProtoMessage()    {}
func (*AttachUsersRolesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{15}
}

func (m *AttachUsersRolesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachUsersRolesRequest.Unmarshal(m, b)
}
func (m *AttachUsersRolesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachUsersRolesRequest.Marshal(b, m, deterministic)
}
func (m *AttachUsersRolesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachUsersRolesRequest.Merge(m, src)
}
func (m *AttachUsersRolesRequest) XXX_Size() int {
	return xxx_messageInfo_AttachUsersRolesRequest.Size(m)
}
func (m *AttachUsersRolesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachUsersRolesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AttachUsersRolesRequest proto.InternalMessageInfo

func (m *AttachUsersRolesRequest) GetRoles() []int64 {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *AttachUsersRolesRequest) GetUsers() []int64 {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *AttachUsersRolesRequest) GetRole() map[string]*AttachUsersRolesRequestUsersMap {
	if m != nil {
		return m.Role
	}
	return nil
}

type AttachUsersRolesRequestUsersMap struct {
	Users                []string `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachUsersRolesRequestUsersMap) Reset()         { *m = AttachUsersRolesRequestUsersMap{} }
func (m *AttachUsersRolesRequestUsersMap) String() string { return proto.CompactTextString(m) }
func (*AttachUsersRolesRequestUsersMap) ProtoMessage()    {}
func (*AttachUsersRolesRequestUsersMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{15, 1}
}

func (m *AttachUsersRolesRequestUsersMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachUsersRolesRequestUsersMap.Unmarshal(m, b)
}
func (m *AttachUsersRolesRequestUsersMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachUsersRolesRequestUsersMap.Marshal(b, m, deterministic)
}
func (m *AttachUsersRolesRequestUsersMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachUsersRolesRequestUsersMap.Merge(m, src)
}
func (m *AttachUsersRolesRequestUsersMap) XXX_Size() int {
	return xxx_messageInfo_AttachUsersRolesRequestUsersMap.Size(m)
}
func (m *AttachUsersRolesRequestUsersMap) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachUsersRolesRequestUsersMap.DiscardUnknown(m)
}

var xxx_messageInfo_AttachUsersRolesRequestUsersMap proto.InternalMessageInfo

func (m *AttachUsersRolesRequestUsersMap) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

type AttachUsersRolesResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachUsersRolesResponse) Reset()         { *m = AttachUsersRolesResponse{} }
func (m *AttachUsersRolesResponse) String() string { return proto.CompactTextString(m) }
func (*AttachUsersRolesResponse) ProtoMessage()    {}
func (*AttachUsersRolesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{16}
}

func (m *AttachUsersRolesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachUsersRolesResponse.Unmarshal(m, b)
}
func (m *AttachUsersRolesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachUsersRolesResponse.Marshal(b, m, deterministic)
}
func (m *AttachUsersRolesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachUsersRolesResponse.Merge(m, src)
}
func (m *AttachUsersRolesResponse) XXX_Size() int {
	return xxx_messageInfo_AttachUsersRolesResponse.Size(m)
}
func (m *AttachUsersRolesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachUsersRolesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AttachUsersRolesResponse proto.InternalMessageInfo

func (m *AttachUsersRolesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AttachUsersTagsRequest struct {
	Tags                 []int64                                   `protobuf:"varint,1,rep,packed,name=tags,proto3" json:"tags,omitempty"`
	Users                []int64                                   `protobuf:"varint,2,rep,packed,name=users,proto3" json:"users,omitempty"`
	TagsMapV             map[string]*AttachUsersTagsRequestTagsMap `protobuf:"bytes,3,rep,name=tagsMapV,proto3" json:"tagsMapV,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *AttachUsersTagsRequest) Reset()         { *m = AttachUsersTagsRequest{} }
func (m *AttachUsersTagsRequest) String() string { return proto.CompactTextString(m) }
func (*AttachUsersTagsRequest) ProtoMessage()    {}
func (*AttachUsersTagsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{17}
}

func (m *AttachUsersTagsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachUsersTagsRequest.Unmarshal(m, b)
}
func (m *AttachUsersTagsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachUsersTagsRequest.Marshal(b, m, deterministic)
}
func (m *AttachUsersTagsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachUsersTagsRequest.Merge(m, src)
}
func (m *AttachUsersTagsRequest) XXX_Size() int {
	return xxx_messageInfo_AttachUsersTagsRequest.Size(m)
}
func (m *AttachUsersTagsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachUsersTagsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AttachUsersTagsRequest proto.InternalMessageInfo

func (m *AttachUsersTagsRequest) GetTags() []int64 {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *AttachUsersTagsRequest) GetUsers() []int64 {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *AttachUsersTagsRequest) GetTagsMapV() map[string]*AttachUsersTagsRequestTagsMap {
	if m != nil {
		return m.TagsMapV
	}
	return nil
}

type AttachUsersTagsRequestTagsMap struct {
	Tags                 []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachUsersTagsRequestTagsMap) Reset()         { *m = AttachUsersTagsRequestTagsMap{} }
func (m *AttachUsersTagsRequestTagsMap) String() string { return proto.CompactTextString(m) }
func (*AttachUsersTagsRequestTagsMap) ProtoMessage()    {}
func (*AttachUsersTagsRequestTagsMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{17, 1}
}

func (m *AttachUsersTagsRequestTagsMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachUsersTagsRequestTagsMap.Unmarshal(m, b)
}
func (m *AttachUsersTagsRequestTagsMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachUsersTagsRequestTagsMap.Marshal(b, m, deterministic)
}
func (m *AttachUsersTagsRequestTagsMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachUsersTagsRequestTagsMap.Merge(m, src)
}
func (m *AttachUsersTagsRequestTagsMap) XXX_Size() int {
	return xxx_messageInfo_AttachUsersTagsRequestTagsMap.Size(m)
}
func (m *AttachUsersTagsRequestTagsMap) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachUsersTagsRequestTagsMap.DiscardUnknown(m)
}

var xxx_messageInfo_AttachUsersTagsRequestTagsMap proto.InternalMessageInfo

func (m *AttachUsersTagsRequestTagsMap) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type AttachTagsResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachTagsResponse) Reset()         { *m = AttachTagsResponse{} }
func (m *AttachTagsResponse) String() string { return proto.CompactTextString(m) }
func (*AttachTagsResponse) ProtoMessage()    {}
func (*AttachTagsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{18}
}

func (m *AttachTagsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachTagsResponse.Unmarshal(m, b)
}
func (m *AttachTagsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachTagsResponse.Marshal(b, m, deterministic)
}
func (m *AttachTagsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachTagsResponse.Merge(m, src)
}
func (m *AttachTagsResponse) XXX_Size() int {
	return xxx_messageInfo_AttachTagsResponse.Size(m)
}
func (m *AttachTagsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachTagsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AttachTagsResponse proto.InternalMessageInfo

func (m *AttachTagsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type SqlMigrationRequest struct {
	Upcount              int64    `protobuf:"varint,1,opt,name=upcount,proto3" json:"upcount,omitempty"`
	Downcount            int64    `protobuf:"varint,2,opt,name=downcount,proto3" json:"downcount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SqlMigrationRequest) Reset()         { *m = SqlMigrationRequest{} }
func (m *SqlMigrationRequest) String() string { return proto.CompactTextString(m) }
func (*SqlMigrationRequest) ProtoMessage()    {}
func (*SqlMigrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{19}
}

func (m *SqlMigrationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SqlMigrationRequest.Unmarshal(m, b)
}
func (m *SqlMigrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SqlMigrationRequest.Marshal(b, m, deterministic)
}
func (m *SqlMigrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SqlMigrationRequest.Merge(m, src)
}
func (m *SqlMigrationRequest) XXX_Size() int {
	return xxx_messageInfo_SqlMigrationRequest.Size(m)
}
func (m *SqlMigrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SqlMigrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SqlMigrationRequest proto.InternalMessageInfo

func (m *SqlMigrationRequest) GetUpcount() int64 {
	if m != nil {
		return m.Upcount
	}
	return 0
}

func (m *SqlMigrationRequest) GetDowncount() int64 {
	if m != nil {
		return m.Downcount
	}
	return 0
}

type SqlMigrationResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SqlMigrationResponse) Reset()         { *m = SqlMigrationResponse{} }
func (m *SqlMigrationResponse) String() string { return proto.CompactTextString(m) }
func (*SqlMigrationResponse) ProtoMessage()    {}
func (*SqlMigrationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_516d2df10a1d8884, []int{20}
}

func (m *SqlMigrationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SqlMigrationResponse.Unmarshal(m, b)
}
func (m *SqlMigrationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SqlMigrationResponse.Marshal(b, m, deterministic)
}
func (m *SqlMigrationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SqlMigrationResponse.Merge(m, src)
}
func (m *SqlMigrationResponse) XXX_Size() int {
	return xxx_messageInfo_SqlMigrationResponse.Size(m)
}
func (m *SqlMigrationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SqlMigrationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SqlMigrationResponse proto.InternalMessageInfo

func (m *SqlMigrationResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*UserRegistrationRequest)(nil), "users.UserRegistrationRequest")
	proto.RegisterType((*Location)(nil), "users.Location")
	proto.RegisterType((*UserRegistrationResponse)(nil), "users.UserRegistrationResponse")
	proto.RegisterType((*UserLoginRequest)(nil), "users.UserLoginRequest")
	proto.RegisterType((*UserLoginResponse)(nil), "users.UserLoginResponse")
	proto.RegisterType((*ListUserRequests)(nil), "users.ListUserRequests")
	proto.RegisterType((*ListUserResponse)(nil), "users.ListUserResponse")
	proto.RegisterType((*CreateRoleRequest)(nil), "users.CreateRoleRequest")
	proto.RegisterType((*CreateRoleResponse)(nil), "users.CreateRoleResponse")
	proto.RegisterType((*CreatePermissionRequest)(nil), "users.CreatePermissionRequest")
	proto.RegisterType((*CreatePermissionResponse)(nil), "users.CreatePermissionResponse")
	proto.RegisterType((*CreateTagRequest)(nil), "users.CreateTagRequest")
	proto.RegisterType((*CreateTagResponse)(nil), "users.CreateTagResponse")
	proto.RegisterType((*AttachRolesPermissionsRequest)(nil), "users.AttachRolesPermissionsRequest")
	proto.RegisterType((*AttachRolesPermissionsResponse)(nil), "users.AttachRolesPermissionsResponse")
	proto.RegisterType((*AttachUsersRolesRequest)(nil), "users.AttachUsersRolesRequest")
	proto.RegisterMapType((map[string]*AttachUsersRolesRequestUsersMap)(nil), "users.AttachUsersRolesRequest.RoleEntry")
	proto.RegisterType((*AttachUsersRolesRequestUsersMap)(nil), "users.AttachUsersRolesRequest.usersMap")
	proto.RegisterType((*AttachUsersRolesResponse)(nil), "users.AttachUsersRolesResponse")
	proto.RegisterType((*AttachUsersTagsRequest)(nil), "users.AttachUsersTagsRequest")
	proto.RegisterMapType((map[string]*AttachUsersTagsRequestTagsMap)(nil), "users.AttachUsersTagsRequest.TagsMapVEntry")
	proto.RegisterType((*AttachUsersTagsRequestTagsMap)(nil), "users.AttachUsersTagsRequest.tagsMap")
	proto.RegisterType((*AttachTagsResponse)(nil), "users.AttachTagsResponse")
	proto.RegisterType((*SqlMigrationRequest)(nil), "users.SqlMigrationRequest")
	proto.RegisterType((*SqlMigrationResponse)(nil), "users.SqlMigrationResponse")
}

func init() {
	proto.RegisterFile("users_srv.proto", fileDescriptor_516d2df10a1d8884)
}

var fileDescriptor_516d2df10a1d8884 = []byte{
	// 944 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x56, 0xcf, 0x6f, 0x1b, 0x45,
	0x14, 0x8e, 0xed, 0x38, 0xb6, 0x5f, 0x12, 0xc5, 0x1d, 0x52, 0xbc, 0xdd, 0x92, 0x62, 0x4d, 0x5b,
	0x61, 0x54, 0xc9, 0x42, 0x81, 0x03, 0x2a, 0x20, 0x51, 0x0a, 0x2a, 0x96, 0xe2, 0x52, 0x6d, 0x13,
	0x10, 0x5c, 0xcc, 0xd4, 0x3b, 0xd9, 0xae, 0x62, 0xef, 0xba, 0x3b, 0x63, 0x47, 0xf9, 0x0b, 0xb8,
	0xf1, 0x7f, 0x72, 0xe4, 0xc6, 0x11, 0xcd, 0xcf, 0x1d, 0x7b, 0xbd, 0x59, 0x04, 0x37, 0x6e, 0xfb,
	0x7e, 0xcc, 0x37, 0xef, 0xfb, 0x66, 0xde, 0x9b, 0x85, 0xa3, 0x25, 0xa3, 0x19, 0x9b, 0xb0, 0x6c,
	0x35, 0x5c, 0x64, 0x29, 0x4f, 0x51, 0x53, 0x3a, 0xf0, 0x5f, 0x35, 0xe8, 0x5d, 0x30, 0x9a, 0x05,
	0x34, 0x8a, 0x19, 0xcf, 0x08, 0x8f, 0xd3, 0x24, 0xa0, 0xef, 0x96, 0x94, 0x71, 0x74, 0x02, 0x70,
	0x19, 0x67, 0x8c, 0x4f, 0x12, 0x32, 0xa7, 0x5e, 0xad, 0x5f, 0x1b, 0x74, 0x82, 0x8e, 0xf4, 0xbc,
	0x24, 0x73, 0x8a, 0xee, 0x43, 0x67, 0x46, 0x4c, 0xb4, 0x2e, 0xa3, 0x6d, 0xe1, 0x90, 0xc1, 0x7b,
	0xd0, 0xa6, 0x73, 0x12, 0xcf, 0x26, 0x71, 0xe8, 0x35, 0x64, 0xac, 0x25, 0xed, 0x51, 0x88, 0x7c,
	0x68, 0x2f, 0x08, 0x63, 0xd7, 0x69, 0x16, 0x7a, 0xbb, 0x6a, 0x99, 0xb1, 0xd1, 0xc7, 0xd0, 0x9d,
	0xa6, 0xc9, 0x65, 0x9c, 0xcd, 0x27, 0x36, 0xa7, 0x29, 0x73, 0x8e, 0xb4, 0xff, 0x95, 0x49, 0x45,
	0xb0, 0xcb, 0x49, 0xc4, 0xbc, 0x3d, 0x19, 0x96, 0xdf, 0xe8, 0x09, 0xb4, 0xcf, 0xd2, 0xa9, 0x24,
	0xe1, 0xb5, 0xfa, 0xb5, 0xc1, 0xfe, 0xe9, 0xd1, 0x50, 0xf2, 0x1c, 0x1a, 0x77, 0x60, 0x13, 0xf0,
	0x30, 0x4f, 0x46, 0x5d, 0x68, 0x9c, 0x11, 0x2e, 0x39, 0xd6, 0x03, 0xf1, 0x29, 0x3d, 0x49, 0x24,
	0x79, 0x09, 0x4f, 0x12, 0xe1, 0x31, 0x78, 0x45, 0xa5, 0xd8, 0x22, 0x4d, 0x18, 0x45, 0x1e, 0xb4,
	0xd8, 0x72, 0x3a, 0xa5, 0x8c, 0x49, 0x8c, 0x76, 0x60, 0x4c, 0xd4, 0x83, 0x96, 0xa8, 0x40, 0xe8,
	0xa0, 0x34, 0xda, 0x13, 0xe6, 0x28, 0xc4, 0x2b, 0xe8, 0x0a, 0xb8, 0xb3, 0x34, 0x8a, 0xad, 0xe2,
	0xae, 0x6a, 0xb5, 0x72, 0xd5, 0xea, 0x1b, 0xaa, 0xb9, 0xb4, 0x1b, 0x55, 0xb4, 0x5f, 0xc2, 0x1d,
	0x67, 0x5f, 0x5d, 0xff, 0x31, 0x34, 0x79, 0x7a, 0x45, 0x13, 0xbd, 0xab, 0x32, 0xd0, 0x43, 0x38,
	0xcc, 0xe8, 0x65, 0x46, 0xd9, 0xdb, 0x89, 0x8a, 0xaa, 0x8d, 0x0f, 0xb4, 0xf3, 0x5c, 0xf8, 0xf0,
	0x23, 0xe8, 0x9e, 0xc5, 0x8c, 0x2b, 0x69, 0x24, 0x0d, 0x26, 0xc4, 0x23, 0xb3, 0x99, 0x06, 0x13,
	0x9f, 0xf8, 0xcf, 0x9a, 0x9b, 0xa6, 0x77, 0xfd, 0x9f, 0x5f, 0xb0, 0x11, 0xdc, 0x79, 0x9e, 0x51,
	0xc2, 0x69, 0x90, 0xce, 0xa8, 0x39, 0x62, 0x04, 0xbb, 0x0e, 0x5b, 0xf9, 0x8d, 0xfa, 0xb0, 0x1f,
	0x52, 0x36, 0xcd, 0xe2, 0x85, 0x04, 0x56, 0x54, 0x5d, 0x17, 0x7e, 0x01, 0xc8, 0x85, 0xfa, 0x27,
	0xb7, 0x2e, 0x4b, 0x67, 0xd4, 0xb9, 0x75, 0xc2, 0x1c, 0x85, 0xf8, 0x07, 0xe8, 0x29, 0xa0, 0x57,
	0x34, 0x9b, 0xc7, 0x8c, 0x39, 0xed, 0xfe, 0xef, 0x2a, 0xfb, 0x19, 0xbc, 0x22, 0x60, 0x65, 0x7d,
	0x0f, 0xe1, 0x70, 0x61, 0xf3, 0xf3, 0x2a, 0x0f, 0x72, 0xe7, 0x28, 0xc4, 0xdf, 0x43, 0x57, 0x41,
	0x9f, 0x93, 0xe8, 0xbf, 0x15, 0xf9, 0xad, 0x39, 0x09, 0x89, 0x54, 0x59, 0xdd, 0x5d, 0xd8, 0xe3,
	0x24, 0xca, 0xcb, 0x6a, 0x72, 0x12, 0x8d, 0x42, 0xfc, 0x13, 0x9c, 0x3c, 0xe3, 0x9c, 0x4c, 0xdf,
	0x8a, 0x43, 0x60, 0x39, 0x5f, 0x66, 0x8a, 0x3b, 0x86, 0xa6, 0x90, 0x59, 0xe0, 0x35, 0x06, 0x8d,
	0x40, 0x19, 0xa2, 0xbc, 0x9c, 0x16, 0xf3, 0xea, 0x32, 0xe6, 0xba, 0xf0, 0x53, 0x78, 0x50, 0x06,
	0x5c, 0x55, 0x2b, 0xfe, 0xad, 0x0e, 0x3d, 0xb5, 0x58, 0xb4, 0x16, 0x93, 0x08, 0xb7, 0xd7, 0x73,
	0x0c, 0x6a, 0xf6, 0xeb, 0x4a, 0x94, 0x81, 0xbe, 0x84, 0x5d, 0x11, 0xf6, 0x1a, 0xfd, 0xc6, 0x60,
	0xff, 0x74, 0xa0, 0x6f, 0x75, 0x09, 0xf2, 0x50, 0x18, 0xdf, 0x25, 0x3c, 0xbb, 0x09, 0xe4, 0x2a,
	0xff, 0x57, 0xe8, 0x58, 0x97, 0xe8, 0xfe, 0x2b, 0x7a, 0x63, 0xba, 0xff, 0x8a, 0xde, 0xa0, 0xaf,
	0xa0, 0xb9, 0x22, 0xb3, 0xa5, 0xea, 0xe2, 0xfd, 0xd3, 0x8f, 0x2a, 0xd0, 0x65, 0x74, 0x4c, 0x16,
	0x81, 0x5a, 0xf5, 0xb4, 0xfe, 0x79, 0xcd, 0xef, 0x43, 0xdb, 0xb8, 0x73, 0x06, 0x82, 0x57, 0x47,
	0x33, 0xc0, 0x9f, 0x81, 0x57, 0x04, 0xac, 0xd4, 0xef, 0xf7, 0x3a, 0xbc, 0xef, 0x2c, 0x3b, 0x27,
	0x11, 0x73, 0xee, 0x9a, 0x1c, 0x00, 0x4a, 0x3d, 0x35, 0x00, 0xb6, 0x8b, 0xf7, 0x02, 0xda, 0x22,
	0x3a, 0x26, 0x8b, 0x1f, 0xb5, 0x80, 0x4f, 0x8a, 0x14, 0x1d, 0xe8, 0xe1, 0xb9, 0xce, 0x56, 0x1a,
	0xda, 0xc5, 0xfe, 0x1b, 0x38, 0x5c, 0x0b, 0x6d, 0xd1, 0xf2, 0x8b, 0x75, 0x2d, 0x1f, 0xdf, 0xbe,
	0x91, 0x46, 0x76, 0x95, 0x3c, 0x81, 0x96, 0xf6, 0xae, 0x31, 0xd4, 0x23, 0x0e, 0x0f, 0x01, 0x29,
	0x2c, 0x05, 0x53, 0x29, 0xe0, 0x18, 0xde, 0x7b, 0xfd, 0x6e, 0x36, 0x8e, 0xa3, 0xf5, 0x9f, 0x07,
	0x0f, 0x5a, 0xcb, 0xc5, 0x34, 0x5d, 0x26, 0xea, 0x55, 0x6d, 0x04, 0xc6, 0x44, 0x1f, 0x40, 0x27,
	0x4c, 0xaf, 0x13, 0x15, 0xab, 0xcb, 0x58, 0xee, 0xc0, 0x9f, 0xc0, 0xf1, 0x3a, 0x5c, 0x55, 0x01,
	0xa7, 0x7f, 0x34, 0xe1, 0xae, 0xe0, 0x3d, 0x26, 0x09, 0x89, 0xe8, 0x9c, 0x26, 0xfc, 0x35, 0xcd,
	0x56, 0xf1, 0x94, 0xa2, 0x0b, 0xf5, 0xc4, 0xba, 0x2f, 0x36, 0x7a, 0xa0, 0xf5, 0x2a, 0xf9, 0xe9,
	0xf1, 0x3f, 0x2c, 0x8d, 0xab, 0x42, 0xf0, 0x0e, 0xfa, 0x1a, 0x3a, 0xf6, 0x05, 0x45, 0x3d, 0x27,
	0xdf, 0x7d, 0xcb, 0x7d, 0xaf, 0x18, 0xb0, 0x08, 0xcf, 0x01, 0xf2, 0x71, 0x8e, 0x4c, 0x66, 0xe1,
	0xb1, 0xf0, 0xef, 0x6d, 0x89, 0x58, 0x90, 0x0b, 0x33, 0x1e, 0xf3, 0x81, 0x61, 0xd9, 0x95, 0xcc,
	0x78, 0xcb, 0xae, 0x6c, 0x64, 0xe3, 0x1d, 0xf4, 0xcc, 0xd4, 0x26, 0xce, 0xdf, 0xd2, 0xdb, 0x1c,
	0xc4, 0xbe, 0x57, 0x0c, 0x58, 0x88, 0xc8, 0xb4, 0xd4, 0xe6, 0x3c, 0x43, 0x8f, 0xd6, 0x6e, 0x6b,
	0xc9, 0x1c, 0xf5, 0x1f, 0x57, 0x64, 0xb9, 0x12, 0x6c, 0xb6, 0xbc, 0x95, 0xa0, 0x64, 0xb8, 0x58,
	0x09, 0xca, 0x66, 0x05, 0xde, 0x41, 0x63, 0x38, 0xda, 0x68, 0x27, 0x74, 0x72, 0x6b, 0x9b, 0xd9,
	0x83, 0x2a, 0x76, 0x0e, 0xde, 0x41, 0x23, 0x38, 0x70, 0xaf, 0x34, 0xf2, 0x75, 0xf2, 0x96, 0xb6,
	0xf1, 0xef, 0x6f, 0x8d, 0x19, 0xa8, 0x6f, 0x5a, 0xbf, 0xa8, 0x89, 0xf3, 0x66, 0x4f, 0xfe, 0xc5,
	0x7f, 0xfa, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x1b, 0x45, 0xf5, 0xd8, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserManagementServiceClient is the client API for UserManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserManagementServiceClient interface {
	UserRegistration(ctx context.Context, in *UserRegistrationRequest, opts ...grpc.CallOption) (*UserRegistrationResponse, error)
	UserLogin(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginResponse, error)
	CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleResponse, error)
	CreatePermission(ctx context.Context, in *CreatePermissionRequest, opts ...grpc.CallOption) (*CreatePermissionResponse, error)
	CreateTags(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error)
	AttachRolesPermissions(ctx context.Context, in *AttachRolesPermissionsRequest, opts ...grpc.CallOption) (*AttachRolesPermissionsResponse, error)
	AttachUsersRoles(ctx context.Context, in *AttachUsersRolesRequest, opts ...grpc.CallOption) (*AttachUsersRolesResponse, error)
	AttachUsersTags(ctx context.Context, in *AttachUsersTagsRequest, opts ...grpc.CallOption) (*AttachTagsResponse, error)
	SqlMigration(ctx context.Context, in *SqlMigrationRequest, opts ...grpc.CallOption) (*SqlMigrationResponse, error)
}

type userManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserManagementServiceClient(cc grpc.ClientConnInterface) UserManagementServiceClient {
	return &userManagementServiceClient{cc}
}

func (c *userManagementServiceClient) UserRegistration(ctx context.Context, in *UserRegistrationRequest, opts ...grpc.CallOption) (*UserRegistrationResponse, error) {
	out := new(UserRegistrationResponse)
	err := c.cc.Invoke(ctx, "/users.UserManagementService/UserRegistration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementServiceClient) UserLogin(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginResponse, error) {
	out := new(UserLoginResponse)
	err := c.cc.Invoke(ctx, "/users.UserManagementService/UserLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementServiceClient) CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleResponse, error) {
	out := new(CreateRoleResponse)
	err := c.cc.Invoke(ctx, "/users.UserManagementService/CreateRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementServiceClient) CreatePermission(ctx context.Context, in *CreatePermissionRequest, opts ...grpc.CallOption) (*CreatePermissionResponse, error) {
	out := new(CreatePermissionResponse)
	err := c.cc.Invoke(ctx, "/users.UserManagementService/CreatePermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementServiceClient) CreateTags(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error) {
	out := new(CreateTagResponse)
	err := c.cc.Invoke(ctx, "/users.UserManagementService/CreateTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementServiceClient) AttachRolesPermissions(ctx context.Context, in *AttachRolesPermissionsRequest, opts ...grpc.CallOption) (*AttachRolesPermissionsResponse, error) {
	out := new(AttachRolesPermissionsResponse)
	err := c.cc.Invoke(ctx, "/users.UserManagementService/AttachRolesPermissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementServiceClient) AttachUsersRoles(ctx context.Context, in *AttachUsersRolesRequest, opts ...grpc.CallOption) (*AttachUsersRolesResponse, error) {
	out := new(AttachUsersRolesResponse)
	err := c.cc.Invoke(ctx, "/users.UserManagementService/AttachUsersRoles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementServiceClient) AttachUsersTags(ctx context.Context, in *AttachUsersTagsRequest, opts ...grpc.CallOption) (*AttachTagsResponse, error) {
	out := new(AttachTagsResponse)
	err := c.cc.Invoke(ctx, "/users.UserManagementService/AttachUsersTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementServiceClient) SqlMigration(ctx context.Context, in *SqlMigrationRequest, opts ...grpc.CallOption) (*SqlMigrationResponse, error) {
	out := new(SqlMigrationResponse)
	err := c.cc.Invoke(ctx, "/users.UserManagementService/SqlMigration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserManagementServiceServer is the server API for UserManagementService service.
type UserManagementServiceServer interface {
	UserRegistration(context.Context, *UserRegistrationRequest) (*UserRegistrationResponse, error)
	UserLogin(context.Context, *UserLoginRequest) (*UserLoginResponse, error)
	CreateRole(context.Context, *CreateRoleRequest) (*CreateRoleResponse, error)
	CreatePermission(context.Context, *CreatePermissionRequest) (*CreatePermissionResponse, error)
	CreateTags(context.Context, *CreateTagRequest) (*CreateTagResponse, error)
	AttachRolesPermissions(context.Context, *AttachRolesPermissionsRequest) (*AttachRolesPermissionsResponse, error)
	AttachUsersRoles(context.Context, *AttachUsersRolesRequest) (*AttachUsersRolesResponse, error)
	AttachUsersTags(context.Context, *AttachUsersTagsRequest) (*AttachTagsResponse, error)
	SqlMigration(context.Context, *SqlMigrationRequest) (*SqlMigrationResponse, error)
}

// UnimplementedUserManagementServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserManagementServiceServer struct {
}

func (*UnimplementedUserManagementServiceServer) UserRegistration(ctx context.Context, req *UserRegistrationRequest) (*UserRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRegistration not implemented")
}
func (*UnimplementedUserManagementServiceServer) UserLogin(ctx context.Context, req *UserLoginRequest) (*UserLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserLogin not implemented")
}
func (*UnimplementedUserManagementServiceServer) CreateRole(ctx context.Context, req *CreateRoleRequest) (*CreateRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRole not implemented")
}
func (*UnimplementedUserManagementServiceServer) CreatePermission(ctx context.Context, req *CreatePermissionRequest) (*CreatePermissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePermission not implemented")
}
func (*UnimplementedUserManagementServiceServer) CreateTags(ctx context.Context, req *CreateTagRequest) (*CreateTagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTags not implemented")
}
func (*UnimplementedUserManagementServiceServer) AttachRolesPermissions(ctx context.Context, req *AttachRolesPermissionsRequest) (*AttachRolesPermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttachRolesPermissions not implemented")
}
func (*UnimplementedUserManagementServiceServer) AttachUsersRoles(ctx context.Context, req *AttachUsersRolesRequest) (*AttachUsersRolesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttachUsersRoles not implemented")
}
func (*UnimplementedUserManagementServiceServer) AttachUsersTags(ctx context.Context, req *AttachUsersTagsRequest) (*AttachTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttachUsersTags not implemented")
}
func (*UnimplementedUserManagementServiceServer) SqlMigration(ctx context.Context, req *SqlMigrationRequest) (*SqlMigrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SqlMigration not implemented")
}

func RegisterUserManagementServiceServer(s *grpc.Server, srv UserManagementServiceServer) {
	s.RegisterService(&_UserManagementService_serviceDesc, srv)
}

func _UserManagementService_UserRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementServiceServer).UserRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserManagementService/UserRegistration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementServiceServer).UserRegistration(ctx, req.(*UserRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementService_UserLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementServiceServer).UserLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserManagementService/UserLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementServiceServer).UserLogin(ctx, req.(*UserLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementService_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementServiceServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserManagementService/CreateRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementServiceServer).CreateRole(ctx, req.(*CreateRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementService_CreatePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementServiceServer).CreatePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserManagementService/CreatePermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementServiceServer).CreatePermission(ctx, req.(*CreatePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementService_CreateTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementServiceServer).CreateTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserManagementService/CreateTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementServiceServer).CreateTags(ctx, req.(*CreateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementService_AttachRolesPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachRolesPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementServiceServer).AttachRolesPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserManagementService/AttachRolesPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementServiceServer).AttachRolesPermissions(ctx, req.(*AttachRolesPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementService_AttachUsersRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachUsersRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementServiceServer).AttachUsersRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserManagementService/AttachUsersRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementServiceServer).AttachUsersRoles(ctx, req.(*AttachUsersRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementService_AttachUsersTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachUsersTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementServiceServer).AttachUsersTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserManagementService/AttachUsersTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementServiceServer).AttachUsersTags(ctx, req.(*AttachUsersTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementService_SqlMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SqlMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementServiceServer).SqlMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserManagementService/SqlMigration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementServiceServer).SqlMigration(ctx, req.(*SqlMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserManagementService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "users.UserManagementService",
	HandlerType: (*UserManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserRegistration",
			Handler:    _UserManagementService_UserRegistration_Handler,
		},
		{
			MethodName: "UserLogin",
			Handler:    _UserManagementService_UserLogin_Handler,
		},
		{
			MethodName: "CreateRole",
			Handler:    _UserManagementService_CreateRole_Handler,
		},
		{
			MethodName: "CreatePermission",
			Handler:    _UserManagementService_CreatePermission_Handler,
		},
		{
			MethodName: "CreateTags",
			Handler:    _UserManagementService_CreateTags_Handler,
		},
		{
			MethodName: "AttachRolesPermissions",
			Handler:    _UserManagementService_AttachRolesPermissions_Handler,
		},
		{
			MethodName: "AttachUsersRoles",
			Handler:    _UserManagementService_AttachUsersRoles_Handler,
		},
		{
			MethodName: "AttachUsersTags",
			Handler:    _UserManagementService_AttachUsersTags_Handler,
		},
		{
			MethodName: "SqlMigration",
			Handler:    _UserManagementService_SqlMigration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users_srv.proto",
}
