// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resource_manager_srv.proto

package resource_manager

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateClusterRequest struct {
	MasterIP             []string `protobuf:"bytes,1,rep,name=masterIP,proto3" json:"masterIP,omitempty"`
	WorkerIP             []string `protobuf:"bytes,2,rep,name=workerIP,proto3" json:"workerIP,omitempty"`
	EtcdIP               []string `protobuf:"bytes,3,rep,name=etcdIP,proto3" json:"etcdIP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateClusterRequest) Reset()         { *m = CreateClusterRequest{} }
func (m *CreateClusterRequest) String() string { return proto.CompactTextString(m) }
func (*CreateClusterRequest) ProtoMessage()    {}
func (*CreateClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6594ff358072bd2f, []int{0}
}

func (m *CreateClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClusterRequest.Unmarshal(m, b)
}
func (m *CreateClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClusterRequest.Marshal(b, m, deterministic)
}
func (m *CreateClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClusterRequest.Merge(m, src)
}
func (m *CreateClusterRequest) XXX_Size() int {
	return xxx_messageInfo_CreateClusterRequest.Size(m)
}
func (m *CreateClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClusterRequest proto.InternalMessageInfo

func (m *CreateClusterRequest) GetMasterIP() []string {
	if m != nil {
		return m.MasterIP
	}
	return nil
}

func (m *CreateClusterRequest) GetWorkerIP() []string {
	if m != nil {
		return m.WorkerIP
	}
	return nil
}

func (m *CreateClusterRequest) GetEtcdIP() []string {
	if m != nil {
		return m.EtcdIP
	}
	return nil
}

type CreateClusterResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateClusterResponse) Reset()         { *m = CreateClusterResponse{} }
func (m *CreateClusterResponse) String() string { return proto.CompactTextString(m) }
func (*CreateClusterResponse) ProtoMessage()    {}
func (*CreateClusterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6594ff358072bd2f, []int{1}
}

func (m *CreateClusterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClusterResponse.Unmarshal(m, b)
}
func (m *CreateClusterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClusterResponse.Marshal(b, m, deterministic)
}
func (m *CreateClusterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClusterResponse.Merge(m, src)
}
func (m *CreateClusterResponse) XXX_Size() int {
	return xxx_messageInfo_CreateClusterResponse.Size(m)
}
func (m *CreateClusterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClusterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClusterResponse proto.InternalMessageInfo

func (m *CreateClusterResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*CreateClusterRequest)(nil), "resourcemanager.CreateClusterRequest")
	proto.RegisterType((*CreateClusterResponse)(nil), "resourcemanager.CreateClusterResponse")
}

func init() {
	proto.RegisterFile("resource_manager_srv.proto", fileDescriptor_6594ff358072bd2f)
}

var fileDescriptor_6594ff358072bd2f = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x4a, 0x2d, 0xce,
	0x2f, 0x2d, 0x4a, 0x4e, 0x8d, 0xcf, 0x4d, 0xcc, 0x4b, 0x4c, 0x4f, 0x2d, 0x8a, 0x2f, 0x2e, 0x2a,
	0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x87, 0xc9, 0x41, 0xa5, 0x94, 0xd2, 0xb8, 0x44,
	0x9c, 0x8b, 0x52, 0x13, 0x4b, 0x52, 0x9d, 0x73, 0x4a, 0x8b, 0x4b, 0x52, 0x8b, 0x82, 0x52, 0x0b,
	0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xa4, 0xb8, 0x38, 0x72, 0x13, 0x41, 0x02, 0x9e, 0x01, 0x12, 0x8c,
	0x0a, 0xcc, 0x1a, 0x9c, 0x41, 0x70, 0x3e, 0x48, 0xae, 0x3c, 0xbf, 0x28, 0x1b, 0x2c, 0xc7, 0x04,
	0x91, 0x83, 0xf1, 0x85, 0xc4, 0xb8, 0xd8, 0x52, 0x4b, 0x92, 0x53, 0x3c, 0x03, 0x24, 0x98, 0xc1,
	0x32, 0x50, 0x9e, 0x92, 0x21, 0x97, 0x28, 0x9a, 0x3d, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42,
	0x12, 0x5c, 0xec, 0xc5, 0xa5, 0xc9, 0xc9, 0xa9, 0xc5, 0xc5, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x1c,
	0x41, 0x30, 0xae, 0x51, 0x05, 0x97, 0x58, 0x10, 0xd4, 0xb5, 0xbe, 0x10, 0xd7, 0x06, 0xa7, 0x16,
	0x95, 0x65, 0x26, 0xa7, 0x0a, 0xc5, 0x71, 0xf1, 0xa2, 0x18, 0x26, 0xa4, 0xaa, 0x87, 0xe6, 0x2f,
	0x3d, 0x6c, 0x9e, 0x92, 0x52, 0x23, 0xa4, 0x0c, 0xe2, 0x26, 0x27, 0xa1, 0x28, 0x01, 0xf4, 0x30,
	0x4c, 0x62, 0x03, 0x07, 0xa0, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xaf, 0x8a, 0x51, 0x5e,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ResourceManagerServiceClient is the client API for ResourceManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResourceManagerServiceClient interface {
	CreateCluster(ctx context.Context, in *CreateClusterRequest, opts ...grpc.CallOption) (*CreateClusterResponse, error)
}

type resourceManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceManagerServiceClient(cc grpc.ClientConnInterface) ResourceManagerServiceClient {
	return &resourceManagerServiceClient{cc}
}

func (c *resourceManagerServiceClient) CreateCluster(ctx context.Context, in *CreateClusterRequest, opts ...grpc.CallOption) (*CreateClusterResponse, error) {
	out := new(CreateClusterResponse)
	err := c.cc.Invoke(ctx, "/resourcemanager.ResourceManagerService/CreateCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceManagerServiceServer is the server API for ResourceManagerService service.
type ResourceManagerServiceServer interface {
	CreateCluster(context.Context, *CreateClusterRequest) (*CreateClusterResponse, error)
}

// UnimplementedResourceManagerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedResourceManagerServiceServer struct {
}

func (*UnimplementedResourceManagerServiceServer) CreateCluster(ctx context.Context, req *CreateClusterRequest) (*CreateClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCluster not implemented")
}

func RegisterResourceManagerServiceServer(s *grpc.Server, srv ResourceManagerServiceServer) {
	s.RegisterService(&_ResourceManagerService_serviceDesc, srv)
}

func _ResourceManagerService_CreateCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceManagerServiceServer).CreateCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resourcemanager.ResourceManagerService/CreateCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceManagerServiceServer).CreateCluster(ctx, req.(*CreateClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ResourceManagerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resourcemanager.ResourceManagerService",
	HandlerType: (*ResourceManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCluster",
			Handler:    _ResourceManagerService_CreateCluster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resource_manager_srv.proto",
}
