// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resource_manager/resource_manager_srv.proto

package resource_manager

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateClusterRequest struct {
	MasterIP             []string `protobuf:"bytes,1,rep,name=masterIP,proto3" json:"masterIP,omitempty"`
	WorkerIP             []string `protobuf:"bytes,2,rep,name=workerIP,proto3" json:"workerIP,omitempty"`
	EtcdIP               []string `protobuf:"bytes,3,rep,name=etcdIP,proto3" json:"etcdIP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateClusterRequest) Reset()         { *m = CreateClusterRequest{} }
func (m *CreateClusterRequest) String() string { return proto.CompactTextString(m) }
func (*CreateClusterRequest) ProtoMessage()    {}
func (*CreateClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f0e92a43094c16b, []int{0}
}

func (m *CreateClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClusterRequest.Unmarshal(m, b)
}
func (m *CreateClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClusterRequest.Marshal(b, m, deterministic)
}
func (m *CreateClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClusterRequest.Merge(m, src)
}
func (m *CreateClusterRequest) XXX_Size() int {
	return xxx_messageInfo_CreateClusterRequest.Size(m)
}
func (m *CreateClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClusterRequest proto.InternalMessageInfo

func (m *CreateClusterRequest) GetMasterIP() []string {
	if m != nil {
		return m.MasterIP
	}
	return nil
}

func (m *CreateClusterRequest) GetWorkerIP() []string {
	if m != nil {
		return m.WorkerIP
	}
	return nil
}

func (m *CreateClusterRequest) GetEtcdIP() []string {
	if m != nil {
		return m.EtcdIP
	}
	return nil
}

type CreateClusterResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateClusterResponse) Reset()         { *m = CreateClusterResponse{} }
func (m *CreateClusterResponse) String() string { return proto.CompactTextString(m) }
func (*CreateClusterResponse) ProtoMessage()    {}
func (*CreateClusterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f0e92a43094c16b, []int{1}
}

func (m *CreateClusterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClusterResponse.Unmarshal(m, b)
}
func (m *CreateClusterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClusterResponse.Marshal(b, m, deterministic)
}
func (m *CreateClusterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClusterResponse.Merge(m, src)
}
func (m *CreateClusterResponse) XXX_Size() int {
	return xxx_messageInfo_CreateClusterResponse.Size(m)
}
func (m *CreateClusterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClusterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClusterResponse proto.InternalMessageInfo

func (m *CreateClusterResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type EventsRequests struct {
	EventType            string             `protobuf:"bytes,1,opt,name=eventType,proto3" json:"eventType,omitempty"`
	ServiceName          string             `protobuf:"bytes,2,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	Time                 string             `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	ActionType           string             `protobuf:"bytes,4,opt,name=actionType,proto3" json:"actionType,omitempty"`
	TraceID              string             `protobuf:"bytes,5,opt,name=traceID,proto3" json:"traceID,omitempty"`
	ErrorCode            string             `protobuf:"bytes,6,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Transaction          *EventsTransaction `protobuf:"bytes,7,opt,name=transaction,proto3" json:"transaction,omitempty"`
	MetaData             map[string][]byte  `protobuf:"bytes,8,rep,name=metaData,proto3" json:"metaData,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *EventsRequests) Reset()         { *m = EventsRequests{} }
func (m *EventsRequests) String() string { return proto.CompactTextString(m) }
func (*EventsRequests) ProtoMessage()    {}
func (*EventsRequests) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f0e92a43094c16b, []int{2}
}

func (m *EventsRequests) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventsRequests.Unmarshal(m, b)
}
func (m *EventsRequests) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventsRequests.Marshal(b, m, deterministic)
}
func (m *EventsRequests) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsRequests.Merge(m, src)
}
func (m *EventsRequests) XXX_Size() int {
	return xxx_messageInfo_EventsRequests.Size(m)
}
func (m *EventsRequests) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsRequests.DiscardUnknown(m)
}

var xxx_messageInfo_EventsRequests proto.InternalMessageInfo

func (m *EventsRequests) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *EventsRequests) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *EventsRequests) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *EventsRequests) GetActionType() string {
	if m != nil {
		return m.ActionType
	}
	return ""
}

func (m *EventsRequests) GetTraceID() string {
	if m != nil {
		return m.TraceID
	}
	return ""
}

func (m *EventsRequests) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *EventsRequests) GetTransaction() *EventsTransaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *EventsRequests) GetMetaData() map[string][]byte {
	if m != nil {
		return m.MetaData
	}
	return nil
}

type EventsTransaction struct {
	EventType            string   `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventsTransaction) Reset()         { *m = EventsTransaction{} }
func (m *EventsTransaction) String() string { return proto.CompactTextString(m) }
func (*EventsTransaction) ProtoMessage()    {}
func (*EventsTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f0e92a43094c16b, []int{3}
}

func (m *EventsTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventsTransaction.Unmarshal(m, b)
}
func (m *EventsTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventsTransaction.Marshal(b, m, deterministic)
}
func (m *EventsTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsTransaction.Merge(m, src)
}
func (m *EventsTransaction) XXX_Size() int {
	return xxx_messageInfo_EventsTransaction.Size(m)
}
func (m *EventsTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_EventsTransaction proto.InternalMessageInfo

func (m *EventsTransaction) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

type EventsResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventsResponse) Reset()         { *m = EventsResponse{} }
func (m *EventsResponse) String() string { return proto.CompactTextString(m) }
func (*EventsResponse) ProtoMessage()    {}
func (*EventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f0e92a43094c16b, []int{4}
}

func (m *EventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventsResponse.Unmarshal(m, b)
}
func (m *EventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventsResponse.Marshal(b, m, deterministic)
}
func (m *EventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsResponse.Merge(m, src)
}
func (m *EventsResponse) XXX_Size() int {
	return xxx_messageInfo_EventsResponse.Size(m)
}
func (m *EventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventsResponse proto.InternalMessageInfo

func (m *EventsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*CreateClusterRequest)(nil), "resourcemanager.CreateClusterRequest")
	proto.RegisterType((*CreateClusterResponse)(nil), "resourcemanager.CreateClusterResponse")
	proto.RegisterType((*EventsRequests)(nil), "resourcemanager.EventsRequests")
	proto.RegisterMapType((map[string][]byte)(nil), "resourcemanager.EventsRequests.MetaDataEntry")
	proto.RegisterType((*EventsTransaction)(nil), "resourcemanager.EventsTransaction")
	proto.RegisterType((*EventsResponse)(nil), "resourcemanager.EventsResponse")
}

func init() {
	proto.RegisterFile("resource_manager/resource_manager_srv.proto", fileDescriptor_2f0e92a43094c16b)
}

var fileDescriptor_2f0e92a43094c16b = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x4d, 0x6f, 0x13, 0x31,
	0x10, 0xd5, 0x66, 0xdb, 0x34, 0x99, 0xb4, 0x50, 0x46, 0xa5, 0xb2, 0x22, 0x3e, 0x56, 0x2b, 0x81,
	0x22, 0x10, 0x41, 0x84, 0x0b, 0x82, 0x1b, 0x49, 0x0f, 0x39, 0x14, 0x45, 0xa6, 0x27, 0x0e, 0x44,
	0xc6, 0x1d, 0x50, 0xd4, 0xec, 0x3a, 0xd8, 0xde, 0x45, 0xf9, 0x0b, 0xfc, 0x34, 0x7e, 0x15, 0x5a,
	0xdb, 0xdb, 0xa4, 0xdb, 0x56, 0xb9, 0xed, 0x7b, 0x6f, 0x3c, 0xfb, 0xe6, 0x8d, 0x0d, 0xaf, 0x35,
	0x19, 0x55, 0x68, 0x49, 0xf3, 0x4c, 0xe4, 0xe2, 0x17, 0xe9, 0xb7, 0x4d, 0x62, 0x6e, 0x74, 0x39,
	0x5c, 0x69, 0x65, 0x15, 0x3e, 0xac, 0xb5, 0x20, 0xa5, 0x3f, 0xe1, 0x64, 0xac, 0x49, 0x58, 0x1a,
	0x2f, 0x0b, 0x63, 0x49, 0x73, 0xfa, 0x5d, 0x90, 0xb1, 0xd8, 0x87, 0x4e, 0x26, 0x2a, 0x62, 0x3a,
	0x63, 0x51, 0x12, 0x0f, 0xba, 0xfc, 0x1a, 0x57, 0xda, 0x1f, 0xa5, 0xaf, 0x9c, 0xd6, 0xf2, 0x5a,
	0x8d, 0xf1, 0x14, 0xda, 0x64, 0xe5, 0xe5, 0x74, 0xc6, 0x62, 0xa7, 0x04, 0x94, 0xbe, 0x83, 0xc7,
	0x8d, 0xff, 0x98, 0x95, 0xca, 0x0d, 0x21, 0x83, 0x03, 0x53, 0x48, 0x49, 0xc6, 0xb0, 0x28, 0x89,
	0x06, 0x1d, 0x5e, 0xc3, 0xf4, 0x6f, 0x0c, 0x0f, 0xce, 0x4a, 0xca, 0xad, 0x09, 0xa6, 0x0c, 0x3e,
	0x81, 0x2e, 0x55, 0xcc, 0xc5, 0x7a, 0x45, 0xae, 0xbc, 0xcb, 0x37, 0x04, 0x26, 0xd0, 0x33, 0xa4,
	0xcb, 0x85, 0xa4, 0x2f, 0x22, 0x23, 0xd6, 0x72, 0xfa, 0x36, 0x85, 0x08, 0x7b, 0x76, 0x91, 0x11,
	0x8b, 0x9d, 0xe4, 0xbe, 0xf1, 0x19, 0x80, 0x90, 0x76, 0xa1, 0x72, 0xd7, 0x74, 0xcf, 0x29, 0x5b,
	0x4c, 0x65, 0xd0, 0x6a, 0x21, 0x69, 0x3a, 0x61, 0xfb, 0x4e, 0xac, 0xa1, 0x73, 0xa3, 0xb5, 0xd2,
	0x63, 0x75, 0x49, 0xac, 0x1d, 0xdc, 0xd4, 0x04, 0x4e, 0xa0, 0x67, 0xb5, 0xc8, 0x8d, 0x6f, 0xc5,
	0x0e, 0x92, 0x68, 0xd0, 0x1b, 0xa5, 0xc3, 0xc6, 0x02, 0x86, 0x7e, 0xc2, 0x8b, 0x4d, 0x25, 0xdf,
	0x3e, 0x86, 0x53, 0xe8, 0x64, 0x64, 0xc5, 0x44, 0x58, 0xc1, 0x3a, 0x49, 0x3c, 0xe8, 0x8d, 0xde,
	0xdc, 0xd3, 0xa2, 0x0e, 0x69, 0x78, 0x1e, 0xea, 0xcf, 0x72, 0xab, 0xd7, 0xfc, 0xfa, 0x78, 0xff,
	0x13, 0x1c, 0xdd, 0x90, 0xf0, 0x18, 0xe2, 0x2b, 0x5a, 0x87, 0x1c, 0xab, 0x4f, 0x3c, 0x81, 0xfd,
	0x52, 0x2c, 0x0b, 0x9f, 0xdd, 0x21, 0xf7, 0xe0, 0x63, 0xeb, 0x43, 0x94, 0x8e, 0xe0, 0xd1, 0x2d,
	0xa7, 0xf8, 0x14, 0xc0, 0xa5, 0x3f, 0xb7, 0x77, 0xed, 0x23, 0x7d, 0xb5, 0xd9, 0xdf, 0xae, 0x65,
	0x8f, 0xfe, 0x45, 0x70, 0xca, 0xc3, 0x5c, 0xe7, 0x7e, 0xae, 0xaf, 0x7e, 0x71, 0xf8, 0x1d, 0x8e,
	0x6e, 0x5c, 0x1d, 0x7c, 0x71, 0x2b, 0x81, 0xbb, 0xae, 0x70, 0xff, 0xe5, 0xae, 0xb2, 0x60, 0x6a,
	0x06, 0x87, 0x63, 0xb5, 0x5c, 0x92, 0xb4, 0xce, 0x2d, 0x3e, 0xdf, 0x11, 0x70, 0xff, 0xfe, 0x02,
	0xdf, 0xf1, 0x33, 0x7e, 0x3b, 0x6e, 0xbe, 0xc1, 0x1f, 0x6d, 0xf7, 0x00, 0xdf, 0xff, 0x0f, 0x00,
	0x00, 0xff, 0xff, 0x04, 0x1e, 0xfa, 0xd3, 0xaf, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ResourceManagerServiceClient is the client API for ResourceManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResourceManagerServiceClient interface {
	CreateCluster(ctx context.Context, in *CreateClusterRequest, opts ...grpc.CallOption) (*CreateClusterResponse, error)
	CollectEvent(ctx context.Context, in *EventsRequests, opts ...grpc.CallOption) (*EventsResponse, error)
}

type resourceManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceManagerServiceClient(cc grpc.ClientConnInterface) ResourceManagerServiceClient {
	return &resourceManagerServiceClient{cc}
}

func (c *resourceManagerServiceClient) CreateCluster(ctx context.Context, in *CreateClusterRequest, opts ...grpc.CallOption) (*CreateClusterResponse, error) {
	out := new(CreateClusterResponse)
	err := c.cc.Invoke(ctx, "/resourcemanager.ResourceManagerService/CreateCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceManagerServiceClient) CollectEvent(ctx context.Context, in *EventsRequests, opts ...grpc.CallOption) (*EventsResponse, error) {
	out := new(EventsResponse)
	err := c.cc.Invoke(ctx, "/resourcemanager.ResourceManagerService/CollectEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceManagerServiceServer is the server API for ResourceManagerService service.
type ResourceManagerServiceServer interface {
	CreateCluster(context.Context, *CreateClusterRequest) (*CreateClusterResponse, error)
	CollectEvent(context.Context, *EventsRequests) (*EventsResponse, error)
}

// UnimplementedResourceManagerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedResourceManagerServiceServer struct {
}

func (*UnimplementedResourceManagerServiceServer) CreateCluster(ctx context.Context, req *CreateClusterRequest) (*CreateClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCluster not implemented")
}
func (*UnimplementedResourceManagerServiceServer) CollectEvent(ctx context.Context, req *EventsRequests) (*EventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectEvent not implemented")
}

func RegisterResourceManagerServiceServer(s *grpc.Server, srv ResourceManagerServiceServer) {
	s.RegisterService(&_ResourceManagerService_serviceDesc, srv)
}

func _ResourceManagerService_CreateCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceManagerServiceServer).CreateCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resourcemanager.ResourceManagerService/CreateCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceManagerServiceServer).CreateCluster(ctx, req.(*CreateClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceManagerService_CollectEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventsRequests)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceManagerServiceServer).CollectEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resourcemanager.ResourceManagerService/CollectEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceManagerServiceServer).CollectEvent(ctx, req.(*EventsRequests))
	}
	return interceptor(ctx, in, info, handler)
}

var _ResourceManagerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resourcemanager.ResourceManagerService",
	HandlerType: (*ResourceManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCluster",
			Handler:    _ResourceManagerService_CreateCluster_Handler,
		},
		{
			MethodName: "CollectEvent",
			Handler:    _ResourceManagerService_CollectEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resource_manager/resource_manager_srv.proto",
}
